# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  uses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    - run: npm ci 
    - run: CI=false npm run build --if-present
    
    - run: mv build asdf
    
    - run: git add ./asdf
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: build
        create_branch: true
        file_pattern: './asdf/'
        push_options: '--force'
        
        commit_options: '--no-verify --signoff'
        status_options: '--untracked-files=no'
        add_options: '-u'
        skip_dirty_check: true  
        skip_fetch: true    
        skip_checkout: true
        disable_globbing: true
